Solr provider redirect
carresemata/xtillion_healthgrades_migration pull request #11
Opened 2024-03-18 18:23 UTC by carresemata

Translated and verified in snowflake that sp_get_solrproviderredirect works

2024-03-19 13:50 UTC, ggandia-xtillion requested changes

2024-03-19 13:50 UTC, ggandia-xtillion commented on migration_original/ODS1Stage/tables/Show/SOLRProviderRedirect/spu_translated_SOLRProviderRedirect.sql
> +    select_statement := ''
Change leading comma to trailing comma

2024-03-22 22:23 UTC, omargoldpr requested changes

2024-03-22 22:23 UTC, omargoldpr commented on migration_original/ODS1Stage/tables/Show/SOLRProviderRedirect/spu_translated_SOLRProviderRedirect.sql
> +CREATE OR REPLACE PROCEDURE SHOW.SP_LOAD_SOLRPROVIDERREDIRECT(IsProviderDeltaProcessing BOOLEAN)
Add database to the procesure name.
```suggestion
CREATE OR REPLACE PROCEDURE ODS1STAGE.SHOW.SP_LOAD_SOLRPROVIDERREDIRECT(IsProviderDeltaProcessing BOOLEAN)
```

2024-03-22 22:23 UTC, omargoldpr commented on migration_original/ODS1Stage/tables/Show/SOLRProviderRedirect/spu_translated_SOLRProviderRedirect.sql
> +        EXECUTE IMMEDIATE merge_statement_else_2;
Why are these execute statements here?

2024-03-25 16:54 UTC, merged