Base.partner
carresemata/xtillion_healthgrades_migration pull request #119
Opened 2024-04-29 09:57 UTC by carresemata

-- All the updates to swimlane have been added as ctes
    -- The update of clienttoproductid that sets the id equal to the id in base.clienttoproduct is not necessary because in the swimlane we have taken this id from this table, thus, we skipped it
    -- When we update the columns we define the new colum as ColumnNameNew and the final select we rename them to ColumnName
    -- The partnerid is actually the clientid

2024-05-03 17:50 UTC, ASanchezXtillion requested changes

2024-05-03 17:50 UTC, ASanchezXtillion commented on migration_original/ODS1Stage/tables/Base/Partner/spu_translated_Partner.sql
I think you might've missed the uuid_string() when inserting a new partner

2024-05-06 13:26 UTC, carresemata commented on migration_original/ODS1Stage/tables/Base/Partner/spu_translated_Partner.sql
According to the original code partner id is the client id and I take it out of the base.client table, it is not created in base.partner

2024-05-06 15:47 UTC, ASanchezXtillion approved these changes

2024-05-06 15:47 UTC, merged