sp_load_solrprovider_freeze
carresemata/xtillion_healthgrades_migration pull request #13
Opened 2024-03-20 16:09 UTC by carresemata

Created sp_load_solrprovider_freeze in snowflake

2024-03-22 22:16 UTC, omargoldpr requested changes

2024-03-22 22:16 UTC, omargoldpr commented on migration_original/ODS1Stage/tables/Show/SOLRProvider_Freeze/spu_translated_SOLRProvider_Freeze.sql
> +CREATE OR REPLACE PROCEDURE SHOW.SP_LOAD_SOLRPROVIDER_FREEZE()
Add the Database to the procesure name
```suggestion
CREATE OR REPLACE PROCEDURE ODS1STAGE.SHOW.SP_LOAD_SOLRPROVIDER_FREEZE() 
```

2024-03-22 22:16 UTC, omargoldpr commented on migration_original/ODS1Stage/tables/Show/SOLRProvider_Freeze/spu_translated_SOLRProvider_Freeze.sql
> +select_statement := 'WITH CTE_ClientCode AS (SELECT
Select in a new line
```suggestion
select_statement := 'WITH CTE_ClientCode AS (
                     SELECT
```

2024-03-25 17:06 UTC, carresemata commented on migration_original/ODS1Stage/tables/Show/SOLRProvider_Freeze/spu_translated_SOLRProvider_Freeze.sql
> +CREATE OR REPLACE PROCEDURE SHOW.SP_LOAD_SOLRPROVIDER_FREEZE()
Done

2024-03-25 17:06 UTC, carresemata commented on migration_original/ODS1Stage/tables/Show/SOLRProvider_Freeze/spu_translated_SOLRProvider_Freeze.sql
> +select_statement := 'WITH CTE_ClientCode AS (SELECT
Done

2024-03-25 17:07 UTC, merged