mid.providerfacility translation
carresemata/xtillion_healthgrades_migration pull request #151
Opened 2024-05-14 18:04 UTC by carresemata

Actions in this PR:
- translate mid.providerfacility
- add view needed for the translation called base.vwupdcfacilitydetail
- solve table dependencies errors that X-ray identified

2024-05-14 19:05 UTC, ggandia-xtillion requested changes

2024-05-14 19:05 UTC, ggandia-xtillion commented on migration_original/ODS1Stage/tables/Mid/ProviderFacility/spu_translated_ProviderFacility.sql
> +    fta.facilityid,
remove columns not in select statement

2024-05-14 19:05 UTC, ggandia-xtillion commented on migration_original/ODS1Stage/tables/Mid/ProviderFacility/spu_translated_ProviderFacility.sql
> +    iff(tqs.ratingssortvalue is null, -1, tqs.ratingssortvalue) <> -1
ifnull

2024-05-14 19:05 UTC, ggandia-xtillion commented on migration_original/ODS1Stage/tables/Mid/ProviderFacility/spu_translated_ProviderFacility.sql
> +select distinct
remove distinct

2024-05-14 19:40 UTC, carresemata commented
Added all changes

2024-05-16 15:14 UTC, ggandia-xtillion approved these changes
![Screenshot_2024-04-04_at_10 27 52_AM-removebg-preview (1)](https://github.com/carresemata/xtillion_healthgrades_migration/assets/149538526/dac93f34-3dcb-48f1-86ff-3ac14b5483d1)

2024-05-16 15:14 UTC, merged