Created Stored Procedure for Show.SOLR Market
carresemata/xtillion_healthgrades_migration pull request #18
Opened 2024-03-21 22:13 UTC by ASanchezXtillion

Verified a sample of 10 marketids, most columns are the same, but xml needs to be tested programatically in order to ensure that it is 100% as expected.

2024-03-22 22:05 UTC, omargoldpr requested changes

2024-03-22 22:05 UTC, omargoldpr commented on migration_original/ODS1Stage/tables/Show/SOLRMarket/spu_translated_SOLRMarket.sql
> +WITH cte_mid AS (
Remove the Limit 100 and add a comment here explaining the reason for this cte (to allow batch processing).

2024-03-22 22:05 UTC, omargoldpr commented on migration_original/ODS1Stage/tables/Show/SOLRMarket/spu_translated_SOLRMarket.sql
> +CREATE OR REPLACE PROCEDURE SP_LOAD_TABLE_SOLRMarket() -- Parameters
add the database and schema to the sp name
```suggestion
CREATE OR REPLACE PROCEDURE ODS1STAGE.SHOW.SP_LOAD_TABLE_SOLRMarket() -- Parameters
```

2024-03-25 21:32 UTC, merged

2024-03-25 21:34 UTC, ggandia-xtillion reviewed
lgtm
![5rN](https://github.com/carresemata/xtillion_healthgrades_migration/assets/149538526/0c4c7da1-8766-4a79-b039-679747197be5)