base.address
carresemata/xtillion_healthgrades_migration pull request #186
Opened 2024-06-06 20:44 UTC by carresemata

2024-06-10 13:13 UTC, ASanchezXtillion requested changes

2024-06-10 13:13 UTC, ASanchezXtillion commented on migration_original/ODS1Stage/tables/Base/CityStatePostalCode/spu_translated_CityStatePostalCode.sql
creo que se te escapo este file de city state postal code, lets get those separated also the report for citystatepostal code even though it might be ugly, for logging purposes

2024-06-10 14:23 UTC, carresemata commented on migration_original/ODS1Stage/tables/Base/CityStatePostalCode/spu_translated_CityStatePostalCode.sql
I needed to change citystatepostalcode to make base.address work

2024-06-24 14:57 UTC, ASanchezXtillion approved these changes
LGTM

2024-06-24 14:57 UTC, merged