base.phone
carresemata/xtillion_healthgrades_migration pull request #217
Opened 2024-06-17 18:08 UTC by carresemata

Everything within margins. Have 50% less phones because we also reduced the num of offices

2024-06-19 15:34 UTC, ASanchezXtillion requested changes
remove the distincts and were gtg

2024-06-19 15:34 UTC, ASanchezXtillion commented on migration_original/ODS1Stage/tables/Base/Phone/spu_translated_Phone.sql
> +    distinct
no distinct

2024-06-19 15:34 UTC, ASanchezXtillion commented on migration_original/ODS1Stage/tables/Base/Phone/spu_translated_Phone.sql
> +        distinct
no distinct

2024-06-20 17:41 UTC, oajimenez approved these changes
LGTM!

2024-06-24 15:01 UTC, ASanchezXtillion approved these changes
LGTM!

2024-06-24 15:01 UTC, merged