cliententitytoclientfeature base table original and translated
carresemata/xtillion_healthgrades_migration pull request #88
Opened 2024-04-20 22:45 UTC by ASanchezXtillion

2024-04-22 12:25 UTC, carresemata reviewed
- In section 0 add: -- Base.ClienttEntityToClientFeature depends on: to keep the same structure
- Are all the logic of the unions still needed? check that in the new json if the clientfeaturecode changed or not

2024-04-22 17:51 UTC, ggandia-xtillion requested changes

2024-04-22 21:48 UTC, ASanchezXtillion commented on migration_original/ODS1Stage/tables/Base/ClientEntityToClientFeature/spu_translated_ClientEntityToClientFeature.sql
> +        *,
It's a bunch of columns🫠. All feature names, it's basically all columns.

2024-04-23 18:35 UTC, ggandia-xtillion commented on migration_original/ODS1Stage/tables/Base/ClientEntityToClientFeature/spu_translated_ClientEntityToClientFeature.sql
> +-- select * from cte_tmp_features;
delete this coment

2024-04-23 18:38 UTC, merged